export * from "./client-section/ClientSection";
export * from "./courses-section/CoursesSection";
export * from "./download-app/DownloadApp";
export * from "./get-in-touch/GetInTouch";
export * from "./hero-card/HeroCard";
export * from "./join-for-free-1/JoinForFree1";
export * from "./hero-section/HeroSection";
export * from "./join-for-free-2/JoinForFree2";
export * from "./superior-section/SuperiorSection";
